# Generated by Django 5.1.1 on 2024-09-23 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(db_column="date_of_birth"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="doctor_name",
            field=models.CharField(db_column="doctor_name", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(db_column="email", max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(db_column="first_name", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_appointment",
            field=models.DateTimeField(db_column="last_appointment"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(db_column="last_name", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_condition",
            field=models.TextField(db_column="medical_condition"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medication_regimen",
            field=models.TextField(db_column="medication_regimen"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="next_appointment",
            field=models.DateTimeField(db_column="next_appointment"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(db_column="phone_number", max_length=15),
        ),
        migrations.AlterModelTable(name="patient", table="patients",),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare_bot.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare_bot.patient",
                    ),
                ),
            ],
        ),
    ]
